/**
 * strfish — Forge config
 *
 * Auto-generated by: forge import --stack <StackName> --profile strfish
 * Generated: 2026-04-25
 *
 * Review this file before running forge apply.
 * Forge will NOT delete or recreate existing resources — it adopts them in place.
 */

import { defineConfig } from '../src/config.js';

export default defineConfig({
  app: 'strfish',
  profile: 'strfish',
  region: 'us-east-1',

  vpc: { mode: 'lookup', vpcId: 'vpc-0daf92af1ac4ec9cc' },

  rds: {
    mode: 'instance',
    engineVersion: '17.6',
    dbName: 'strfish',
    masterUsername: 'strfish_admin',
    instanceClass: 'db.t4g.micro',
    storage: 20,
    deletionProtection: false,
    proxy: false,
  },

  cognito: {
    poolName: 'strfish-users',
    emailSignup: true,
    clients: [
      {
        name: 'strfish-app',
        authFlows: ['ALLOW_REFRESH_TOKEN_AUTH', 'ALLOW_USER_PASSWORD_AUTH', 'ALLOW_USER_SRP_AUTH'],
        generateSecret: false,
        callbackUrls: ['https://example.com'],
      }
    ],
    triggers: { preTokenGeneration: 'strfish-pre-token-generation', postConfirmation: 'strfish-post-confirmation' },
  },

  lambda: [
    {
      name: 'strfish-api',
      runtime: 'nodejs20.x',
      memory: 512,
      timeout: 30,
      handler: 'index.handler',
      architecture: 'x86_64',
      vpc: true,
      env: {
        DOCUMENT_BUCKET: 'strfish-documents-380648616162-us-east-1',
        DB_PORT: '5432',
        NODE_OPTIONS: '--enable-source-maps',
        DB_NAME: 'strfish',
        COGNITO_CLIENT_ID: 'pf1uia8psu308epuiuf4j0nm3',
        COGNITO_USER_POOL_ID: 'us-east-1_oq8xweXqA',
        DB_HOST: 'strfish-databaseb269d8bb-vpfp79x41wqq.c6rukc82ytww.us-east-1.rds.amazonaws.com',
        DB_SECRET_ARN: 'REDACTED — set via AWS Console or CLI',
      },
    },
    {
      name: 'STRfish-CustomEmailSenderLambdaA1C15DAA-ddg7hOYfR9V8',
      runtime: 'nodejs20.x',
      memory: 256,
      timeout: 15,
      handler: 'index.handler',
      architecture: 'x86_64',
      env: {
        KEY_ARN: 'arn:aws:kms:us-east-1:380648616162:key/a8c37c5f-37c8-4d98-b62e-0020d86ee32e',
        RESEND_API_KEY: 'REDACTED — set via AWS Console or CLI',
        KEY_ID: 'a8c37c5f-37c8-4d98-b62e-0020d86ee32e',
      },
    },
    {
      name: 'strfish-post-confirmation',
      runtime: 'nodejs20.x',
      memory: 256,
      timeout: 10,
      handler: 'post-confirmation.handler',
      architecture: 'x86_64',
      vpc: true,
      env: {
        DB_PORT: '5432',
        DB_NAME: 'strfish',
        DB_HOST: 'strfish-databaseb269d8bb-vpfp79x41wqq.c6rukc82ytww.us-east-1.rds.amazonaws.com',
        DB_SECRET_ARN: 'REDACTED — set via AWS Console or CLI',
      },
    },
    {
      name: 'strfish-pre-token-generation',
      runtime: 'nodejs20.x',
      memory: 256,
      timeout: 10,
      handler: 'pre-token-generation.handler',
      architecture: 'x86_64',
      vpc: true,
      env: {
        DB_PORT: '5432',
        DB_NAME: 'strfish',
        DB_HOST: 'strfish-databaseb269d8bb-vpfp79x41wqq.c6rukc82ytww.us-east-1.rds.amazonaws.com',
        DB_SECRET_ARN: 'REDACTED — set via AWS Console or CLI',
      },
    },
  ],

  apiGateway: {
    name: 'strfish-api',
    corsOrigins: ['*'],
    catchAll: true,
    publicRoutes: ['POST /auth/login', 'POST /auth/refresh', 'POST /auth/reset-password', 'POST /auth/signup', 'POST /auth/forgot-password', 'GET /health', 'POST /auth/verify'],
    cognitoPoolId: 'us-east-1_oq8xweXqA',
    cognitoClientId: 'pf1uia8psu308epuiuf4j0nm3',
  },

  s3: [
    {
      name: 'strfish-documents-{account}-{region}',
      encryption: 'AES256',
      blockPublicAccess: true,
      lifecycle: [
        { prefix: '', expirationDays: 90 }
      ],
    },
    {
      name: 'strfish-web-{account}-{region}',
      encryption: 'AES256',
      blockPublicAccess: false,
    },
  ],
});
